### ISSUE TITLE
Can you give a example real time retrive the edge coverage  when use the tools ?

### ISSUE THREAD

**Issue by ricardo-kcc** [ThePatrickStar/fuzzer-data-collector#2]
if want to get the below pic, I need to use you tool real time. So, Can you give a example real time retrive the edge coverage  when use the tools ?
Thanks.
![image](https://user-images.githubusercontent.com/64991294/172637666-c91a5d15-8cf3-4ae8-802c-6ed9d8c3b9ab.png)

**Comment by ThePatrickStar** [comment]
Hi, would you like to count the edge coverage when the fuzzer is running?
Or do you just want the pictures after the fuzzer has stopped?

**Comment by ricardo-kcc** [comment]
Hi, ThePatrickStar. I want to count the edge coverge by using afl-showmap when the fuzzer running.

**Comment by ricardo-kcc** [comment]
hello, @ThePatrickStar . I have got below output after using showmap(my data). 
![image](https://user-images.githubusercontent.com/64991294/174440259-290d9a21-f6d1-4737-8da5-d6a9f0a98b78.png)
And， I have successed plot the line chart when used the slot_edge.txt(afl-showmaps generated).  But, I don't know how to get the data file when plot scatter and boxplot. Please could you help me ? 
Thanks!
