### ISSUE TITLE
the path of `slot_edge.txt`  in toml file

### ISSUE THREAD

**Issue by ricardo-kcc** [ThePatrickStar/fuzzer-data-collector#4]
the path of `slot_edge.txt`  in toml file is a absolute path or relative path ？
https://github.com/ThePatrickStar/fuzzer-data-collector/blob/7ba2d9a79d35243cc3504aa8e4a27e8a205e26ec/stat_plot/test/test_config.toml#L6

And it could't read the below file correctly when using relative path. 
![$@E6FPHAYDPR1J9$EAI1C(J](https://user-images.githubusercontent.com/64991294/177022464-e8635e5f-c678-4870-845d-e70a009220cd.png)
the tested data is [slot_edge.txt](https://github.com/ThePatrickStar/fuzzer-data-collector/files/9033986/slot_edge.txt)
 Could anyone help me ?

**Comment by ThePatrickStar** [comment]
Sorry for the late reply, was quite busy recently.
Pls try to enlarge the "max_time" and change the "bucket" to "min" in the configuration toml file.
If you meet further problems, pls let me know.

**Comment by ricardo-kcc** [comment]
thanks!
